import { IMesh } from '../_interfaces/interfaces'

export const dataAstmMeshes: IMesh[] = [
  { astm: '5"', iso: 112, serie: 'gruesa', isUsual: false },
  { astm: '4"', iso: 100, serie: 'gruesa', isUsual: false },
  { astm: '3-1/2"', iso: 83, serie: 'gruesa', isUsual: false },
  { astm: '3"', iso: 75, serie: 'gruesa', isUsual: false },
  { astm: '2-1/2"', iso: 63, serie: 'gruesa', isUsual: false },
  { astm: '2"', iso: 50, serie: 'gruesa', isUsual: true },
  { astm: '1-3/4"', iso: 45, serie: 'gruesa', isUsual: false },
  { astm: '1-1/2"', iso: 38.1, serie: 'gruesa', isUsual: false },
  { astm: '1-1/4"', iso: 31.5, serie: 'gruesa', isUsual: false },
  { astm: '1"', iso: 25, serie: 'gruesa', isUsual: true },
  { astm: '7/8"', iso: 22.4, serie: 'gruesa', isUsual: false },
  { astm: '3/4"', iso: 19, serie: 'gruesa', isUsual: true },
  { astm: '5/8"', iso: 16, serie: 'gruesa', isUsual: false },
  { astm: '1/2"', iso: 12.5, serie: 'gruesa', isUsual: true },
  { astm: '7/16"', iso: 11.2, serie: 'gruesa', isUsual: false },
  { astm: '3/8"', iso: 9.5, serie: 'gruesa', isUsual: true },
  { astm: '5/16"', iso: 8, serie: 'gruesa', isUsual: false },
  { astm: '1/4"', iso: 6.3, serie: 'fina', isUsual: true },
  { astm: 'No. 3-1/2', iso: 5.6, serie: 'fina', isUsual: false },
  { astm: 'No. 4', iso: 4.75, serie: 'fina', isUsual: true },
  { astm: 'No. 5', iso: 4, serie: 'fina', isUsual: false },
  { astm: 'No. 6', iso: 3.35, serie: 'fina', isUsual: false },
  { astm: 'No. 7', iso: 2.8, serie: 'fina', isUsual: false },
  { astm: 'No. 8', iso: 2.36, serie: 'fina', isUsual: true },
  { astm: 'No. 10', iso: 2, serie: 'fina', isUsual: true },
  { astm: 'No. 12', iso: 1.7, serie: 'fina', isUsual: false },
  { astm: 'No. 14', iso: 1.4, serie: 'fina', isUsual: false },
  { astm: 'No. 16', iso: 1.18, serie: 'fina', isUsual: false },
  { astm: 'No. 18', iso: 1, serie: 'fina', isUsual: false },
  { astm: 'No. 20', iso: 0.85, serie: 'fina', isUsual: true },
  { astm: 'No. 25', iso: 0.71, serie: 'fina', isUsual: false },
  { astm: 'No. 30', iso: 0.6, serie: 'fina', isUsual: false },
  { astm: 'No. 35', iso: 0.5, serie: 'fina', isUsual: false },
  { astm: 'No. 40', iso: 0.425, serie: 'fina', isUsual: true },
  { astm: 'No. 45', iso: 0.355, serie: 'fina', isUsual: false },
  { astm: 'No. 50', iso: 0.3, serie: 'fina', isUsual: true },
  { astm: 'No. 60', iso: 0.25, serie: 'fina', isUsual: true },
  { astm: 'No. 70', iso: 0.212, serie: 'fina', isUsual: false },
  { astm: 'No. 80', iso: 0.18, serie: 'fina', isUsual: true },
  { astm: 'No. 100', iso: 0.15, serie: 'fina', isUsual: true },
  { astm: 'No. 120', iso: 0.125, serie: 'fina', isUsual: false },
  { astm: 'No. 140', iso: 0.106, serie: 'fina', isUsual: false },
  { astm: 'No. 170', iso: 0.09, serie: 'fina', isUsual: false },
  { astm: 'No. 200', iso: 0.075, serie: 'fina', isUsual: true },
  { astm: 'No. 230', iso: 0.063, serie: 'fina', isUsual: false },
  { astm: 'No. 270', iso: 0.053, serie: 'fina', isUsual: false },
  { astm: 'No. 325', iso: 0.045, serie: 'fina', isUsual: false },
  { astm: 'No. 400', iso: 0.038, serie: 'fina', isUsual: false },
]
